Repository rendayigit/SpaceLoader, pull requests merged in 2022-03, with the labels that each got.

#12 applied path fix
  common.h
Labels: Server, Client

#13 .vscode now supports 64 bit msys kits
  .vscode/c_cpp_properties.json
  .vscode/cmake-kits.json
  .vscode/launch.json
  .vscode/settings.json
  scripts/run client test.bat
  scripts/run client.bat
  scripts/run gui.bat
  scripts/run server.bat
Labels: enhancement

#26 2 implement parseinternalcommands
  Commands/PluginInterface.h
  Commands/Server/addUser/AddUser.h
  Commands/Server/addUser/CMakeLists.txt
  Commands/Server/addUser/main.cpp
  Commands/Server/getUserList/CMakeLists.txt
  Commands/Server/getUserList/GetUserList.h
  Commands/Server/getUserList/main.cpp
  Server/server.cpp
  Server/server.h
Labels: Server

#31 22 use define instead of pragma once
  lib/Logger/logger.h
  lib/XML/xml.h
  lib/YAML/yaml.h
Labels: enhancement

#30 fix static warnings and improve .clang tidy
  .clang-tidy
Labels: enhancement
